fixtures:
  repositories:
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
      ref: '1.0.3'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.13.1'
    epel:
      repo: 'git://github.com/stahnma/puppet-module-epel.git'
      ref: '1.0.2'
  symlinks:
    python: "#{source_dir}"
